<a href="https://colab.research.google.com/github/Sanchit7972/Sanchit7972-Data_Science_Lab_SE_A_19/blob/main/Simple_python_program%20/DS03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

print("Enter the 9 elements for a 3x3 matrix, row by row. Separate elements by spaces.")

matrix_elements = []
for i in range(3):
    while True:
        try:
            row_str = input(f"Enter elements for row {i+1} (e.g., '1 2 3'): ")
            row_elements = list(map(float, row_str.split()))
            if len(row_elements) != 3:
                raise ValueError("Please enter exactly 3 elements for the row.")
            matrix_elements.append(row_elements)
            break
        except ValueError as e:
            print(f"Invalid input: {e}. Please try again.")

# Create a 3x3 square matrix from user input
A = np.array(matrix_elements)

# Compute its determinant
det_A = np.linalg.det(A)

print("\nMatrix A:\n", A)
print("Determinant of A:", det_A)

# Check if the matrix is invertible (determinant is not zero)
if det_A != 0:
    # Compute the inverse of the matrix
    A_inv = np.linalg.inv(A)
    print("\nInverse of A:\n", A_inv)
else:
    print("\nDeterminant is zero, so the matrix is not invertible and its inverse cannot be calculated.")

Enter the 9 elements for a 3x3 matrix, row by row. Separate elements by spaces.
Enter elements for row 1 (e.g., '1 2 3'): 3 4 5
Enter elements for row 2 (e.g., '1 2 3'): 3 4 2
Enter elements for row 3 (e.g., '1 2 3'): 2 3 7

Matrix A:
 [[3. 4. 5.]
 [3. 4. 2.]
 [2. 3. 7.]]
Determinant of A: 3.0000000000000018

Inverse of A:
 [[ 7.33333333 -4.33333333 -4.        ]
 [-5.66666667  3.66666667  3.        ]
 [ 0.33333333 -0.33333333 -0.        ]]


In [7]:
import numpy as np

# Define the coefficient matrix A
A = np.array([[2, 3],
              [4, 5]])

# Define the constant terms vector b
b = np.array([10, 20])

# Solve the system of linear equations A*x = b
x = np.linalg.solve(A, b)

print("System of equations:")
print("2x + 3y = 10")
print("4x + 5y = 20")
print("\nSolution:")
print(f"x = {x[0]:.2f}")
print(f"y = {x[1]:.2f}")

System of equations:
2x + 3y = 10
4x + 5y = 20

Solution:
x = 5.00
y = 0.00
