<a href="https://colab.research.google.com/github/Sanchit7972/Sanchit7972-Data_Science_Lab_SE_A_19/blob/main/Simple_python_program/DSEXP03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
# Create a 3x3 square matrix
A = np.array([[1, 2, 3],
              [0, 1, 4],
              [5, 6, 0]])

# Compute determinant
det_A = np.linalg.det(A)

print("Matrix A:\n", A)
print("\nDeterminant of A:", det_A)


Matrix A:
 [[1 2 3]
 [0 1 4]
 [5 6 0]]

Determinant of A: 0.9999999999999964


In [3]:
# Find inverse of the matrix
A_inv = np.linalg.inv(A)

print("Inverse of Matrix A:\n", A_inv)


Inverse of Matrix A:
 [[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


In [5]:
# Coefficient matrix
coefficients = np.array([[2, 3],
                          [4, 5]])

# Constant terms
constants = np.array([10, 20])

# Solve the system of linear equations
solution = np.linalg.solve(coefficients, constants)

print("Solution:")
print("x =", solution[0])
print("y =", solution[1])


Solution:
x = 5.0
y = 0.0
